version: '3.8'

services:
  lomay:
    build:
      context: ./ecommerce
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/lomay/static
      - media_volume:/home/app/lomay/media
    expose:
      - 8000
    restart: always
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/lomay/static
      - media_volume:/home/app/lomay/media
    ports:
      - 80:80
    depends_on:
      - lomay

volumes:
  postgres_data:
  static_volume:
  media_volume:
