version: '3.8'

services:
  web:
    build: ./ecommerce
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    restart: always
    depends_on:
      - db
  db:
    # image: postgres:13.0-alpine
    image: postgres:13-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aman
      - POSTGRES_PASSWORD=aman
      - POSTGRES_DB=lomay

volumes:
  postgres_data:
